# Generated by Django 4.1.3 on 2023-07-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('En cours de livraison', 'en cours de livraions'), ('En cours de traitement', 'en cours de traitement'), ('Payee', 'payee'), ('Payee et Livree', 'payee et livree'), ('Livree', 'payee et livree')], default='En cours de traitement', max_length=150),
        ),
    ]
