# Generated by Django 4.1.3 on 2023-07-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panier', '0003_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackpayment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
