# Generated by Django 4.1.3 on 2023-08-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panier', '0006_order_status_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
