# Generated by Django 4.1.3 on 2023-08-09 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panier', '0007_article_is_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='is_favorite',
            new_name='isFavorite',
        ),
    ]
