# Generated by Django 4.1.3 on 2023-08-14 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panier', '0009_notifications'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notifications',
            new_name='NotificationsModel',
        ),
    ]
