# Generated by Django 4.1.3 on 2023-08-14 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panier', '0010_rename_notifications_notificationsmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotificationsModel',
            new_name='Notification',
        ),
    ]
