# Generated by Django 4.1.3 on 2023-08-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panier', '0012_notification_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/article_images')),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='images',
        ),
        migrations.AddField(
            model_name='article',
            name='images',
            field=models.ManyToManyField(to='panier.image'),
        ),
    ]
