# Generated by Django 4.1.3 on 2023-08-29 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panier', '0015_alter_article_images_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='firstName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='lastName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='article',
            name='images',
            field=models.ManyToManyField(to='panier.image'),
        ),
        migrations.AlterField(
            model_name='order',
            name='userId',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
