# Generated by Django 3.2.21 on 2023-09-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panier', '0016_order_adresse_order_firstname_order_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='panier.Image'),
        ),
    ]
