# Generated by Django 3.2.21 on 2023-09-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panier', '0017_alter_article_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='images',
            field=models.ManyToManyField(blank=True, to='panier.Image'),
        ),
    ]
