# Generated by Django 3.2.21 on 2023-09-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panier', '0018_alter_article_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='articleInStockSecurite',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
