# Generated by Django 3.2.21 on 2023-09-26 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panier', '0019_article_articleinstocksecurite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendeur',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='panier.user')),
            ],
            options={
                'abstract': False,
            },
            bases=('panier.user',),
        ),
        migrations.CreateModel(
            name='Acheteur',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='panier.user')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acheteurs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('panier.user',),
        ),
    ]
