# Generated by Django 3.2.21 on 2023-09-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panier', '0020_acheteur_vendeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='acheteur',
            name='status',
            field=models.CharField(choices=[('ACHETEUR', 'ACHETEUR'), ('VENDEUR', 'VENDEUR')], default='ACHETEUR', max_length=16),
        ),
    ]
