# Generated by Django 3.2.21 on 2023-09-26 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panier', '0021_acheteur_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acheteur',
            name='status',
        ),
    ]
