# Generated by Django 3.2.21 on 2023-09-27 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panier', '0022_remove_acheteur_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acheteur',
            old_name='createdBy',
            new_name='vendeurId',
        ),
    ]
