# Generated by Django 3.2.21 on 2023-09-27 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panier', '0024_remove_user_tailleur'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendeur',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/logo/'),
        ),
        migrations.AddField(
            model_name='vendeur',
            name='raisonSocial',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='vendeur',
            name='region',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='vendeur',
            name='ville',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='acheteur',
            name='vendeurId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acheteurs_created', to='panier.vendeur'),
        ),
    ]
