# Generated by Django 3.2.21 on 2023-09-27 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panier', '0025_auto_20230927_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acheteur',
            old_name='vendeurId',
            new_name='vendeur_id',
        ),
    ]
