# Generated by Django 3.2.21 on 2023-09-27 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panier', '0026_rename_vendeurid_acheteur_vendeur_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendeur',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vendeur_relate', to='panier.user'),
            preserve_default=False,
        ),
    ]
