# Generated by Django 3.2.21 on 2023-09-27 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panier', '0027_vendeur_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendeur',
            name='user_id',
        ),
    ]
