# Generated by Django 3.2.21 on 2023-09-27 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panier', '0029_auto_20230927_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='category',
            name='userId',
        ),
        migrations.AddField(
            model_name='article',
            name='vendeurId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='panier.vendeur'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='vendeurId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='panier.vendeur'),
            preserve_default=False,
        ),
    ]
