# Generated by Django 4.1.3 on 2023-09-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panier', '0030_auto_20230927_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('ACHETEUR', 'ACHETEUR'), ('ADMIN', 'ADMIN'), ('VENDEUR', 'VENDEUR')], max_length=20),
        ),
    ]
