# Generated by Django 4.1.3 on 2023-09-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panier', '0031_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('ACHETEUR', 'ACHETEUR'), ('ADMIN', 'ADMIN'), ('VENDEUR', 'VENDEUR')], default='ADMIN', max_length=20),
        ),
    ]
