# Generated by Django 4.1.3 on 2023-09-30 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panier', '0032_alter_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='userId',
        ),
        migrations.AddField(
            model_name='order',
            name='vendeur_id',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='panier.vendeur'),
        ),
    ]
