# Generated by Django 4.1.3 on 2023-09-30 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panier', '0033_remove_order_userid_order_vendeur_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='acheteur_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panier.acheteur'),
        ),
    ]
