"""
Django settings for kayjeund project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
import dj_database_url
load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
from dotenv import dotenv_values
env = dotenv_values(".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0ctlf%p#ww*l00*tcs)f-=3g=3dwy#a6zh##a%fa6s0@$9sy$_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",
    'drf_yasg',
    "panier",
    "dashboard",
    'whitenoise.runserver_nostatic',
    "corsheaders",
]

# REST_FRAMEWORK = {
#     'DEFAULT_PAGINATION_CLASS': 'kayjeund.pagination.CustomPageNumberPagination',
#     'PAGE_SIZE': 155 # Une valeur suffisamment grande pour obtenir toutes les commandes sur une seule page
# }

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'kayjeund.pagination.CustomPageNumberPagination',
    # 'PAGE_SIZE': 10
}




MIDDLEWARE = [
     "corsheaders.middleware.CorsMiddleware",
    # ...
    'django.contrib.sessions.middleware.SessionMiddleware',
    "django.middleware.csrf.CsrfViewMiddleware",
    # ...
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
    # ...
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # "corsheaders.middleware.CorsMiddleware",
    # 'django.contrib.sessions.middleware.SessionMiddleware',
    # "django.middleware.csrf.CsrfViewMiddleware",
    # "corsheaders.middleware.CorsPostCsrfMiddleware",
    # 'django.middleware.security.SecurityMiddleware',
    # 'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    # 'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'django.contrib.messages.middleware.MessageMiddleware',
    # 'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'kayjeund.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kayjeund.wsgi.application'

AUTH_USER_MODEL = "panier.User"
# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'easy-market-v2',
#         'USER': 'postgres',
#         'PASSWORD': 'allstar2002',
#         'HOST': '127.0.0.1',
#         'PORT': '5432',
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'easy-market',
#         'USER': 'postgres',
#         'PASSWORD': 'allstar2002',
#         'HOST': '127.0.0.1',
#         'PORT': '5432',
#     }
# }


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env['DB_NAME'],
        'USER': env['DB_USER'],
        'PASSWORD': env['DB_PASSWORD'],
        'HOST': env['DB_HOST'],
        'PORT': env['DB_PORT'],
    } 
}



DATABASES['default']  = dj_database_url.parse(env["RENDER_DB"])

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'



MEDIA_URL = '/uploads/'# comment l’URL de référence permettant au navigateur d’accéder aux fichiers via Http.
MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads')
STATIC_ROOT = os.path.join(BASE_DIR, "static/")

STATIC_FILES_DIRS = (
    os.path.join(BASE_DIR, 'static')
)

# for cors 
CSRF_HEADER_NAME = "HTTP_X_CSRFTOKEN"
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-csrf-token",
    "csrftoken",
    "x-requested-with",
    "http_x_csrftoken"
]

CSRF_USE_SESSIONS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1",
    "https://fewnu-compta.web.app",
    "http://fewnu-django.herokuapp.com",
    "http://*.herokuapp.com",
    "http://fewnu-compta.web.app",
    "http://*.web.app",
    "https://api-easy.fewnu.app"
]
CSRF_TRUSTED_ORIGINS = [
    "https://127.0.0.1:3000",
    "http://fewnu-django.herokuapp.com",
    "http://*.herokuapp.com",
    "http://127.0.0.1",
    "http://127.0.0.1:3000",
    "http://fewnu-compta.web.app",
    "http://localhost:3000",
    "http://*.web.app",
    "https://fewnu-compta.web.app",
    "https://api-easy.fewnu.app",
    'https://*.ngrok-free.app'
]
CORS_ALLOW_CREDENTIALS = True


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
